=== sholloway/agents-playground/agents_playground/spatial/landscape/file/landscape.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://agents-playground.com/landscape-definition.schema.json",
  "title": "Landscape Definition",
  "description": "A geometric landscape for use in a simulation.",
  "type": "object",
  "properties": {
    "file_characteristics":{
      "description": "Metadata about a landscape file.",
      "type": "object",
      "properties": {
        "author":{
          "description":"Can be any string but intended to be First Name Last Name.",
          "type": "string"
        },
        "license":{
          "description":"The license type for this attribute.",
          "type": "string"
        },
        "contact":{
          "description":"Contact information. Could be anything.",
          "type": "string"
        },
        "creation_time":{
          "description":"When the file was initially created in the format YYYY-MM-DD hh:mm:ss.",
          "type": "string",
          "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6} UTC"
        },
        "updated_time":{
          "description":"When the file was last updated in the format YYYY-MM-DD hh:mm:ss.",
          "type": "string",
          "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6} UTC"
        }
      },
      "required": []
    },
    "characteristics":{
      "description": "The defining characteristics of a landscape. Specifies the shape of the lattice.",
      "type": "object",
      "properties": {
        "mesh_type":{
          "type": "string",
          "pattern": "\\b(?:SQUARE_TILE)\\b"
        },
        "landscape_uom_system":{
          "type": "string",
          "pattern": "\\b(?:METERS|FEET)\\b"
        },
        "tile_size_uom":{
          "type": "string",
          "pattern": "\\b(?:POINT|PICA|INCH|FEET|YARD|MILE|LEAGUE|PICOMETER|NANOMETER|MICROMETER|MILLIMETER|CENTIMETER|DECIMETER|METER|DECAMETER|HECTOMETER|KILOMETER|MEGAMETER|GIGAMETER|TERAMETER)\\b"
        },
        "tile_width":{
          "type": "number"
        },
        "tile_height":{
          "type": "number"
        },
        "tile_depth":{
          "type": "number"
        }
      },
      "required": [
        "mesh_type", 
        "landscape_uom_system", 
        "tile_size_uom", 
        "tile_width", 
        "tile_height", 
        "tile_depth"
      ]
    },
    "physicality":{
      "description": "The physical aspects of the landscape.",
      "type": "object",
      "properties": {
        "gravity_uom": {
          "type": "string",
          "pattern": "\\b(?:METERS_PER_SECOND_SQUARED|FEET_PER_SECOND_SQUARED)\\b"
        },
        "gravity_strength": {
          "type": "number"
        }
      },
      "required": ["gravity_uom", "gravity_strength"]
    },
    "custom_attributes":{
      "description": "A generic section to enable developers to add custom values to a landscape definition.",
      "type":"object"
    },
    "tiles":{
      "description": "The tiles in the landscape",
      "type": "array",
      "properties": {},
      "required": []
    }
  },
  "required": ["characteristics", "tiles"]
}

=== sholloway/agents-playground/agents_playground/spatial/landscape/file/landscape_example.json
{
  "file_characteristics":{
    "author": "John Smith",
    "license": "MIT",
    "contact": "john.smith@smiths.com",
    "creation_time": "2024-03-01 12:42:54.510655 UTC",
    "updated_time": "2024-03-01 12:42:54.510655 UTC"
  },
  "characteristics":{
    "mesh_type": "SQUARE_TILE",
    "landscape_uom_system": "METERS",
    "tile_size_uom": "METER",
    "tile_width": 1,
    "tile_height": 1,
    "tile_depth": 1
  },
  "physicality":{
    "gravity_uom":"METERS_PER_SECOND_SQUARED",
    "gravity_strength": 9.8
  },
  "custom_attributes":{
    "ignore":123
  },
  "tiles": [
    [0, 0, 0, 1],
    [0, 0, 1, 6],
    [0, 0, 2, 7],
    [1, 0, 0, 8],
    [-1, 0, 0, 9],
    [0, 0, -1, 10],
    [0, 0, -2, 11]
  ]
}

=== sholloway/agents-playground/agents_playground/templates/base_sim_files/landscape.json
{
  "file_characteristics":{
    "author": "${author}",
    "license": "${license}",
    "contact": "${contact}",
    "creation_time": "${creation_time}"
  },
  "characteristics":{
    "mesh_type": "SQUARE_TILE",
    "landscape_uom_system": "${landscape_uom_system}",
    "tile_size_uom": "${tile_size_uom}",
    "tile_width": 1,
    "tile_height": 1,
    "tile_depth": 1
  },
  "physicality":{
    "gravity_uom":"METERS_PER_SECOND_SQUARED",
    "gravity_strength": 9.8
  },
  "custom_attributes":{
    "ignore":123
  },
  "tiles": [
    [0, 0, 0, 3],[1, 0, 0, 3],[2, 0, 0, 3],[3, 0, 0, 3],[4, 0, 0, 3],[5, 0, 0, 3],[6, 0, 0, 3],[7, 0, 0, 3],[8, 0, 0, 3],[9, 0, 0, 3],
    [0, 0, 1, 3],[1, 0, 1, 3],[2, 0, 1, 3],[3, 0, 1, 3],[4, 0, 1, 3],[5, 0, 1, 3],[6, 0, 1, 3],[7, 0, 1, 3],[8, 0, 1, 3],[9, 0, 1, 3],
    [0, 0, 2, 3],[1, 0, 2, 3],[2, 0, 2, 3],[3, 0, 2, 3],[4, 0, 2, 3],[5, 0, 2, 3],[6, 0, 2, 3],[7, 0, 2, 3],[8, 0, 2, 3],[9, 0, 2, 3],
    [0, 0, 3, 3],[1, 0, 3, 3],[2, 0, 3, 3],[3, 0, 3, 3],[4, 0, 3, 3],[5, 0, 3, 3],[6, 0, 3, 3],[7, 0, 3, 3],[8, 0, 3, 3],[9, 0, 3, 3],
    [0, 0, 4, 3],[1, 0, 4, 3],[2, 0, 4, 3],[3, 0, 4, 3],[4, 0, 4, 3],[5, 0, 4, 3],[6, 0, 4, 3],[7, 0, 4, 3],[8, 0, 4, 3],[9, 0, 4, 3],
    [0, 0, 5, 3],[1, 0, 5, 3],[2, 0, 5, 3],[3, 0, 5, 3],[4, 0, 5, 3],[5, 0, 5, 3],[6, 0, 5, 3],[7, 0, 5, 3],[8, 0, 5, 3],[9, 0, 5, 3],
    [0, 0, 6, 3],[1, 0, 6, 3],[2, 0, 6, 3],[3, 0, 6, 3],[4, 0, 6, 3],[5, 0, 6, 3],[6, 0, 6, 3],[7, 0, 6, 3],[8, 0, 6, 3],[9, 0, 6, 3],
    [0, 0, 7, 3],[1, 0, 7, 3],[2, 0, 7, 3],[3, 0, 7, 3],[4, 0, 7, 3],[5, 0, 7, 3],[6, 0, 7, 3],[7, 0, 7, 3],[8, 0, 7, 3],[9, 0, 7, 3],
    [0, 0, 8, 3],[1, 0, 8, 3],[2, 0, 8, 3],[3, 0, 8, 3],[4, 0, 8, 3],[5, 0, 8, 3],[6, 0, 8, 3],[7, 0, 8, 3],[8, 0, 8, 3],[9, 0, 8, 3],
    [0, 0, 9, 3],[1, 0, 9, 3],[2, 0, 9, 3],[3, 0, 9, 3],[4, 0, 9, 3],[5, 0, 9, 3],[6, 0, 9, 3],[7, 0, 9, 3],[8, 0, 9, 3],[9, 0, 9, 3]
  ]
}
