=== sholloway/agents-playground/agents_playground/tasks/file/tasks.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://agents-playground.com/tasks-definition.schema.json",
    "title": "Simulation Tasks Definition",
    "description": "A simulation scene registered tasks to leverage.",
    "type": "object",
    "properties": {
        "initial_tasks": { "$ref": "#/$defs/task_name_list" },
        "per_frame_tasks": { "$ref": "#/$defs/task_name_list" },
        "render_tasks": { "$ref" : "#/$defs/task_name_list" }, 
        "shutdown_tasks" : { "$ref": "#/$defs/task_name_list" }
    },
    "required": [
        "initial_tasks", 
        "per_frame_tasks", 
        "render_tasks", 
        "shutdown_tasks"
    ], 
    "$defs": {
        "task_name_list":{
            "description": "A list of task names.",
            "type": "array",
            "items": { 
                "type": "string"
            },
            "uniqueItems": true
        }
    }
}

=== sholloway/agents-playground/agents_playground/tasks/file/default_tasks.json
{
    "initial_tasks":[
        "load_scene",
        "load_landscape_mesh",
        "initialize_graphics_pipeline",
        "prepare_landscape_renderer",
        "prepare_fps_overlay_renderer",
        "create_simulation_context",
        "start_simulation_loop"
    ],
    "per_frame_tasks":[
    ],
    "render_tasks":[
        "calculate_aspect_ratio",
        "set_texture_target",
        "construct_projection_matrix",
        "bind_camera_data",
        "configure_color_attachment",
        "create_depth_texture",
        "create_depth_stencil_attachment",
        "create_gpu_encoder",
        "create_render_pass_encoder",
        "render_landscape",
        "render_fps",
        "end_render_pass"
    ], 
    "shutdown_tasks":[
      "end_simulation"
    ]
}
